### ISSUE TITLE
A more readable xparse spec

### ISSUE THREAD

**Issue by joewiz** [expkg-zone58/ex-xparse#3]
The README points to https://lists.w3.org/Archives/Public/public-expath/2015Feb/att-0003/xparse.html as the location for the spec. On my browser that page is unreadable:

> ![Screen Shot 2019-05-31 at 8 39 22 AM](https://user-images.githubusercontent.com/59118/58706298-a3944800-837f-11e9-9354-1d971e612076.png)

I wonder if John Lumley would provide his original file and if we could resurrect this as an EXPath spec + implementation? I can see this as being a very useful pedagogical and debugging tool.

Thoughts @adamretter @ChristianGruen?

**Comment by apb2006** [comment]
Just on the readability issue: 
Some time ago the page was changed to being served with `https:` but the css is still referenced with `http:`.  

Chrome and Edge block this. Firefox is not so fussy.

**Comment by adamretter** [comment]
@joewiz I don't have much time to invest in this at the moment, but it sounds reasonable.
